import { z } from 'zod'

/**
 * Schema for a single order within a strategy proposal.
 * The AI must produce orders matching this exact shape.
 */
export const strategyOrderSchema = z.object({
  side: z
    .enum(['buy', 'sell'])
    .describe('Order side: "buy" to purchase base asset, "sell" to sell base asset'),
  price: z
    .number()
    .positive()
    .describe(
      'Limit order price in quote asset units (e.g., 8.50 means 8.50 USDT per INJ)'
    ),
  quantity: z
    .number()
    .positive()
    .describe(
      'Order quantity in base asset units (e.g., 2.5 means 2.5 INJ)'
    ),
  percentOfTotal: z
    .number()
    .min(0)
    .max(100)
    .describe(
      'Percentage of total capital allocated to this order, 0-100. All orders should sum to ~100.'
    ),
})

/**
 * Schema for a complete strategy proposal generated by the AI.
 * Validated against market data before presenting to the user.
 */
export const strategyProposalSchema = z.object({
  strategyType: z
    .enum([
      'dca',
      'stop-loss',
      'scale-in',
      'take-profit',
      'limit-buy',
      'range-accumulate',
      'bracket',
    ])
    .describe(
      'The type of trading strategy. Must match one of the supported preset types.'
    ),
  marketId: z
    .string()
    .describe(
      'Injective spot market ID (hex string). Will be injected by the system -- AI should leave empty or echo the provided value.'
    ),
  baseDenom: z
    .string()
    .describe(
      'Base token denomination string (e.g., "inj"). Will be injected by the system.'
    ),
  quoteDenom: z
    .string()
    .describe(
      'Quote token denomination string (e.g., "peggy0xdAC17F958D2ee523a2206206994597C13D831ec7" for USDT). Will be injected by the system.'
    ),
  orders: z
    .array(strategyOrderSchema)
    .min(1)
    .max(20)
    .describe(
      'Array of limit orders to place. Minimum 1, maximum 20 orders.'
    ),
  totalCapitalRequired: z
    .number()
    .positive()
    .describe(
      'Total capital needed in quote asset units (e.g., 100 means 100 USDT). Should roughly equal sum of (price * quantity) across all orders.'
    ),
  priceRange: z.object({
    min: z
      .number()
      .positive()
      .describe('Lowest price in the strategy range (quote asset units)'),
    max: z
      .number()
      .positive()
      .describe('Highest price in the strategy range (quote asset units)'),
  }).describe('The price range spanned by all orders in the strategy'),
  splitCount: z
    .number()
    .int()
    .min(1)
    .max(20)
    .describe(
      'Number of order splits. Should match orders.length.'
    ),
  worstCaseOutcome: z
    .string()
    .describe(
      'Honest description of the worst-case scenario if this strategy fully executes (e.g., "All buy orders fill and price drops further -- you hold INJ at an average cost of $7.20")'
    ),
  reasoning: z
    .string()
    .describe(
      'Brief explanation of why this strategy makes sense given current market conditions and the user intent'
    ),
})

/** Inferred TypeScript type for a single strategy order */
export type StrategyOrder = z.infer<typeof strategyOrderSchema>

/** Inferred TypeScript type for a complete strategy proposal */
export type StrategyProposal = z.infer<typeof strategyProposalSchema>
